
const iconList = {
    200:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    201:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    202:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    210:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    211:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    212:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    221:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    230:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    231:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    232:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],

    300:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    301:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    302:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    310:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    311:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    312:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    313:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    314:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    321:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],

    500:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    501:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    502:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    503:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    504:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    511:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    520:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    521:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    522:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    531:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],

    600:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    601:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    602:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    611:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    612:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    613:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    615:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    616:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    620:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    621:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    622:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],

    701:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    711:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    721:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    731:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    741:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    751:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    761:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    762:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    771:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],
    781:    ['wi-day-thunderstorm', 'wi-night-thunderstorm'],

    800:    ['wi-day-sunny', 'wi-night-clear'],
    801:    ['wi-day-cloudy', 'wi-night-alt-cloudy'],
    802:    ['wi-day-cloudy', 'wi-night-alt-cloudy'],
    803:    ['wi-day-cloudy', 'wi-night-alt-cloudy'],
    804:    ['wi-day-cloudy', 'wi-night-alt-cloudy'],

}


export { iconList };